### ISSUE TITLE
Esmond cleaning script failure in nightly repo

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#271]
Hi Andy,

I have my pS Dev test server on pS toolkit and it is setup with nightly on a CentOS 6.9 Linux.
Running  **/usr/lib/perfsonar/scripts/clean_esmond_db.sh** gives these errors.

```
Traceback (most recent call last):
  File "./util/ps_remove_data.py", line 73, in <module>
    from esmond.api.models import PSMetadata, PSPointToPointSubject, PSEventTypes, PSMetadataParameters
  File "/usr/lib/esmond/esmond/api/models.py", line 5, in <module>
    from django.contrib.auth.models import User, Permission
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/contrib/auth/models.py", line 4, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/contrib/auth/base_user.py", line 52, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/db/models/base.py", line 105, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/apps/registry.py", line 237, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

This had been working previously and stopped working in August.
The production systems I have are still not affected.

Regards,
Ivan

**Comment by arlake228** [comment]
Reopening as this appears to still be an issue on CentOS 6.

**Comment by arlake228** [comment]
I was able to recreate and think I found the cause. Basically the python script needed a few lines up top to initialize Django. No idea why it didn't fail in earlier testing, but should be good now. RPM is building and will be ins taging shortly. Version is 2.1.2-0.2.b1

**Comment by arlake228** [comment]
Also worth noting the update is in the esmond RPM.

**Comment by igarny** [comment]
This issue is resolved now.
Thanks Andy
