### ISSUE TITLE
Django Internal Server Error after fresh ISO install

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#286]
After fresh Fullinstall of ISO 4.0.2 Toolkit GUI presents " Error loading test listing: Internal Server Error" under Test Results.
Host is IPv4 only.

[psudouser@localhost esmond]$ cat django.log
2017-12-14 13:49:38,309 [ERROR] /usr/lib/esmond/lib/python2.7/site-packages/django/core/handlers/exception.py: Internal Server Error: /esmond/perfsonar/archive/
Traceback (most recent call last):
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
    response = middleware_method(request)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/middleware/common.py", line 62, in process_request
    if self.should_redirect_with_slash(request):
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/middleware/common.py", line 80, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/urls/base.py", line 157, in is_valid_path
    resolve(path, urlconf)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/urls/base.py", line 27, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/urls/resolvers.py", line 270, in resolve
    for pattern in self.url_patterns:
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/esmond/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/esmond/esmond/urls.py", line 10, in <module>
    from esmond.api.api_v2 import (
  File "/usr/lib/esmond/esmond/api/api_v2.py", line 52, in <module>
    raise ConnectionException(str(e))
ConnectionException: '"System Manager can\'t connect to Cassandra at localhost:9160 - Could not connect to localhost:9160"'
[psudouser@localhost esmond]$

[root@cowania2 psudouser]# systemctl status cassandra
● cassandra.service - SYSV: Starts and stops Cassandra
   Loaded: loaded (/etc/rc.d/init.d/cassandra; bad; vendor preset: disabled)
   Active: active (exited) since Thu 2017-12-14 13:57:04 CET; 21min ago
     Docs: man:systemd-sysv-generator(8)

Dec 14 13:57:03 cowania2.man.poznan.pl systemd[1]: cassandra.service: control process exited, code=exited status=1
Dec 14 13:57:03 cowania2.man.poznan.pl systemd[1]: Unit cassandra.service entered failed state.
Dec 14 13:57:03 cowania2.man.poznan.pl systemd[1]: cassandra.service failed.
Dec 14 13:57:03 cowania2.man.poznan.pl systemd[1]: Starting SYSV: Starts and stops Cassandra...
Dec 14 13:57:03 cowania2.man.poznan.pl su[6069]: (to cassandra) root on none
Dec 14 13:57:04 cowania2.man.poznan.pl cassandra[6045]: Starting Cassandra: OK
Dec 14 13:57:04 cowania2.man.poznan.pl systemd[1]: Started SYSV: Starts and stops Cassandra.
[root@cowania2 psudouser]# 

[root@cowania2 psudouser]# pscheduler task --archive @/usr/share/pscheduler/psc-archiver-esmond.json idle —duration PT5S
Unable to read archive file: [Errno 2] No such file or directory: '/usr/share/pscheduler/psc-archiver-esmond.json'
[root@cowania2 psudouser]#

[root@cowania2 psudouser]# cat /var/log/messages
Dec 14 14:33:51 localhost journal: safe_run/runner ERROR    Exception: DatabaseError: server closed the connection unexpectedly#012#011This probably means the server terminated abnormally#012#011before or while processing the request.#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 72, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 932, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 842, in main_program#012    """, [refresh]);#012DatabaseError: server closed the connection unexpectedly#012#011This probably means the server terminated abnormally#012#011before or while processing the request.
Dec 14 14:33:51 localhost journal: safe_run/runner ERROR    Waiting 11.0 seconds before restarting
Dec 14 14:33:51 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[16094]: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Dec 14 14:33:51 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[16094]: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Dec 14 14:33:51 localhost journal: tool-powstream/run ERROR    powstream failed to complete execution: <type 'exceptions.IOError'>
Dec 14 14:33:51 localhost journal: tool-powstream/run ERROR    powstream failed to complete execution: <type 'exceptions.IOError'>
Dec 14 14:33:54 localhost powstream[16374]: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Dec 14 14:34:01 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[16140]: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Dec 14 14:34:01 localhost journal: tool-powstream/run ERROR    powstream exited with error, will attempt restart: powstream[16140]: NTP: STA_NANO should be set. Make sure ntpd is running, and your NTP configuration is good.
Dec 14 14:34:01 localhost journal: tool-powstream/run ERROR    powstream failed to complete execution: <type 'exceptions.IOError'>
Dec 14 14:34:01 localhost journal: tool-powstream/run ERROR    powstream failed to complete execution: <type 'exceptions.IOError'>
Dec 14 14:34:02 localhost journal: safe_run/runner ERROR    Restarting: ['/usr/libexec/pscheduler/daemons/runner', '--daemon', '--pid-file', '/var/run/pscheduler-runner.pid', '--dsn', '@/etc/pscheduler/database/database-dsn']
Dec 14 14:34:02 localhost journal: runner INFO     Started
Dec 14 14:34:03 localhost journal: safe_run/runner ERROR    Program threw an exception after 0:00:00.551676
Dec 14 14:34:03 localhost journal: safe_run/runner ERROR    Exception: DatabaseError: server closed the connection unexpectedly#012#011This probably means the server terminated abnormally#012#011before or while processing the request.#012#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/pscheduler/saferun.py", line 72, in safe_run#012    function()#012  File "/usr/libexec/pscheduler/daemons/runner", line 932, in <lambda>#012    pscheduler.safe_run(lambda: main_program())#012  File "/usr/libexec/pscheduler/daemons/runner", line 842, in main_program#012    """, [refresh]);#012DatabaseError: server closed the connection unexpectedly#012#011This probably means the server terminated abnormally#012#011before or while processing the request.
Dec 14 14:34:03 localhost journal: safe_run/runner ERROR    Waiting 11.25 seconds before restarting

**Comment by szymontrocha** [comment]
Python seems to be missing:
[root@cowania2 psudouser]# ls -la /opt/rh/
total 0
drwxr-xr-x. 2 root root  6 Sep  7 01:11 .
drwxr-xr-x. 3 root root 16 Dec 14 14:31 ..
[root@cowania2 psudouser]#

**Comment by szymontrocha** [comment]
[root@cowania2 psudouser]# cd /usr/lib/esmond
[root@cowania2 psudouser]# . bin/activate
(esmond)[root@cowania2 esmond]#  python esmond/manage.py add_api_key_user perfsonar
Traceback (most recent call last):
  File "esmond/manage.py", line 2, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
(esmond)[root@cowania2 esmond]#

**Comment by starboarder2001** [comment]
Same issue....
