### ISSUE TITLE
Error retrieving data for the Graphs "elasticsearch.exceptions.RequestError"

### ISSUE THREAD

**Issue by adrialla** [perfsonar/toolkit#430]
I have the toolkit version 5.0.0-0.b1.1.el7 upgraded from version 4.4. Installed on CentOS 7.

I get error when I try to get the data from the Graphs. I get error retrieving data? 

https://pfs-node.rash.al/perfsonar-graphs/?source=37.139.112.125&dest=62.40.114.63&url=https%3A%2F%2Fpfs-node.rash.al%2Fesmond%2Fperfsonar%2Farchive%2F&timeframe=1d#start=1677753415&end=1677839815&summaryWindow=86400&timeframe=86400&timesel=1d&startDate=Thu%20Mar%2002%202023%2011%3A36%3A55%20GMT%2B0100&endDate=Fri%20Mar%2003%202023%2011%3A36%3A55%20GMT%2B0100&hide_failures=true

I get the same for all the tests?

when diagnosing from browser I get the error below:

https://pfs-node.rash.al/esmond/perfsonar/archive/?format=json&pscheduler-test-type=dns&measurement-agent=37.139.112.125&pscheduler-dns-query=37.139.112.78

elasticsearch.exceptions.RequestError

elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [pscheduler.start_time] in order to sort on')
Traceback (most recent call last)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/usr/lib/perfsonar/elmond/app.py", line 59, in list_metadata

    metadata = emd.search(q=request.args, request_url=request.url, paginate=True)

    File "/usr/lib/perfsonar/elmond/metadata.py", line 151, in search

    res = self.es.search(index="pscheduler_*", body=dsl)

    File "/usr/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped

    return func(*args, params=params, **kwargs)

    File "/usr/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 805, in search

    "GET", _make_path(index, "_search"), params=params, body=body

    File "/usr/lib/python3.6/site-packages/elasticsearch/transport.py", line 350, in perform_request

    timeout=timeout,

    File "/usr/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request

    self._raise_error(response.status, raw_data)

    File "/usr/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error

    status_code, error_message, additional_info

    elasticsearch.exceptions.RequestError: RequestError(400, 'search_phase_execution_exception', 'No mapping found for [pscheduler.start_time] in order to sort on')

The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.

To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

    dump() shows all variables in the frame
    dump(obj) dumps all that's known about the object

**Comment by adrialla** [comment]
after the upgrade to 5.0.1, there was no error and the graphs are showing correctly.
